server:
  port: 8080

knife4j:
  enable: true
  openapi:
    title: lingotube接口文档
    description: "lingotube文档"
    email: zhanghuyi@itcast.cn
    concat: Moncoder
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.moncoder.lingo.user.controller