server:
  port: 8084
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: localhost:9200
