server:
  port: 8082
spring:
  boot:
    admin:
      client:
        url: http://localhost:8086
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 200MB # 单文件上传大小
      max-request-size: 1GB # 总文件大小

