server:
  port: 8081
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
lingo:
  tube:
    jwt:
      location: classpath:jwt.jks # 秘钥地址
      alias: jwt # 秘钥别名
      password: lingotube # 秘钥文件密码
      tokenTTL: 300m # 登录有效期
